
import { Inter } from "next/font/google";
import "./globals.css";
import useThemeStore from "@/store/theme.store";
import { useEffect } from "react";
import Header from "@/components/header/Header";
import { Metadata } from "next";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased min-h-screen h-[620vh]`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
